name: Deploy Emergent Site to OVH
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout du code
        uses: actions/checkout@v4

      - name: 🏗️ Installer et Construire le Frontend
        working-directory: ./frontend
        run: |
          # Nettoyage et installation forcée
          rm -rf node_modules package-lock.json
          npm install ajv --save-dev --legacy-peer-deps
          npm install --legacy-peer-deps
          DISABLE_ESLINT_PLUGIN=true npm run build


      - name: 🚀 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Craco crée un dossier 'build'
          local-dir: ./frontend/build/
          server-dir: ./www/
          delete-destination: false
